<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="NlpToolkit-Classification" Version="1.0.7" />
      <PackageReference Include="NlpToolkit-WordToVec" Version="1.0.5" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Sequence" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ComputationalGraph-CS\ComputationalGraph\ComputationalGraph.csproj" />
    </ItemGroup>

</Project>